### PR TITLE
go test: add longer wait time to proposer 1

### PR DESCRIPTION
**Pull request by Tu-V**

### CODE REVIEW

**Comment by kkdai** [comment]
Hi,

Thank you for your PR, would you please explain why you want to extend the waiting time for the proposer?

**Comment by iamtu** [comment]
Hi, when I first fork and run "go test", it error like this.

**Comment by Tu-V** [comment]
HI, when I first fork and run "go test", it errors like this. 

2019/11/26 21:52:52 accept:check propose.  117 117
2019/11/26 21:52:52 ID: 3  Accept
2019/11/26 21:52:52 Send msg from: 3  send to 200  val: WrongValue  typ: 4
2019/11/26 21:52:52 Recev msg from: 1  send to 200  val: WrongValue  typ: 4
2019/11/26 21:52:52 Learner: recev msg: {1 200 4 117 0 WrongValue}
2019/11/26 21:52:52 Recev msg from: 2  send to 200  val: WrongValue  typ: 4
2019/11/26 21:52:52 Learner: recev msg: {2 200 4 117 0 WrongValue}
2019/11/26 21:52:52 Recev msg from: 3  send to 200  val: WrongValue  typ: 4
2019/11/26 21:52:52 Learner: recev msg: {3 200 4 117 0 WrongValue}
--- FAIL: TestTwoProsers (0.01s)
    paxos_test.go:99: Learner learn wrong proposal. Expect:'ExpectValue'. learnValue WrongValue
FAIL
exit status 1
FAIL    github.com/kkdai/paxos  1.035s

So I just to make sure that the proposer2.run() will run in other goroutine after the proposer1 run.

**Comment by kkdai** [comment]
Got it, thank you.

**Pull request merged**
